name: glee
description: A new Flutter application.



version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1
  flutter_screenutil: ^2.3.0
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3
  spotify: ^0.3.2
  sqflite: ^1.3.0+1
  path_provider: ^1.6.7
  flutter_spinkit: ^3.1.0
  font_awesome_flutter: ^8.8.1
  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  flutter_local_notifications: ^0.8.4
  datetime_picker_formfield:
  dynamic_theme: ^1.0.1
  flutter_launcher_icons: ^0.7.4
  provider: ^2.0.1
  get_it: ^4.0.2
  http: ^0.12.0+2
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.7+3
  flutter_animation_progress_bar: ^1.0.0
  animated_text_kit: ^2.2.0
  audioplayers: ^0.15.1
  confetti: ^0.5.2
  url_launcher: ^5.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/Glee/



  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
